Add possibility tail all error logs

diff --git a/compose/bin/log b/compose/bin/log
--- a/compose/bin/log
+++ b/compose/bin/log
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 LOGS_PATH="/var/www/html/var/log"
+
 CONTAINER_NAME="$(basename "$(pwd)")-phpfpm-1"
 
 echo -e "\033[94mDeveloped by \033[34mYevhen \033[93mZvieriev\033[0m"
@@ -24,12 +25,11 @@ function search_errors() {
     local found_errors=false
 
     for log_file in ./log/*.log; do
-        local errors=$(grep -E -r --color=always "\(ERROR\|FATAL\|CRITICAL\)" "$log_file" | sed -E 's/\(ERROR\|FATAL\|CRITICAL\)/\o033[31m&\o033[0m/g' || true)
-        local warnings=$(grep -E -r --color=always "\bWARNING\b" "$log_file" | sed -E 's/WARNING/\o033[33m&\o033[0m/g' || true)
-        local info=$(grep -E -r --color=always "INFO" "$log_file" | sed -E 's/INFO/\o033[32m&\o033[0m/g' || true)
-        local debug=$(grep -E -r --color=always "DEBUG" "$log_file" | sed -E 's/DEBUG/\o033[33m&\o033[0m/g' || true)
+        local errors=$(grep -E -r --color=always "\(ERROR\|FATAL\|CRITICAL\)" "$log_file" | format_log_output || true)
+        local warnings=$(grep -E -r --color=always "\bWARNING\b" "$log_file" | format_log_output || true)
+        local info=$(grep -E -r --color=always "INFO" "$log_file" | format_log_output || true)
+        local debug=$(grep -E -r --color=always "DEBUG" "$log_file" | format_log_output || true)
         if [ -n "$errors" ] || [ -n "$warnings" ] || [ -n "$info" ] || [ -n "$debug" ]; then
-
             found_errors=true
             echo -e "\n\033[1;33m----------------------------------------\033[0m"
             echo -e "\033[1;33mLog File: \033[32m$(basename "$log_file")\033[0m"
@@ -47,9 +47,22 @@ function search_errors() {
     fi
 }
 
-function tail_logs() {
-    local log_file_paths="$1"
-    docker exec -it "$CONTAINER_NAME" tail -f $log_file_paths
+function tail_all_logs() {
+    local log_file="$1"
+    docker exec -it "$CONTAINER_NAME" tail -f "$LOGS_PATH/$log_file" | while IFS= read -r line; do
+        echo "$line" | format_log_output | tee /dev/tty
+    done
+}
+
+function tail_error_logs() {
+    local log_file="$1"
+    docker exec -it "$CONTAINER_NAME" tail -f "$LOGS_PATH/$log_file" | grep -E --line-buffered "(ERROR|FATAL|CRITICAL)" | while IFS= read -r line; do
+        echo -e "$line" | format_log_output | tee /dev/tty
+    done
+}
+
+function format_log_output() {
+    sed -E 's/(ERROR|FATAL|CRITICAL)/\o033[31m\1\o033[0m/g' | sed -E 's/\bWARNING\b/\o033[33m&\o033[0m/g' | sed -E 's/INFO/\o033[32m&\o033[0m/g' | sed -E 's/DEBUG/\o033[36m&\o033[0m/g'
 }
 
 while true; do
@@ -64,23 +77,35 @@ while true; do
     if [ "$option" == "1" ]; then
         show_logs
     elif [ "$option" == "2" ]; then
-    	show_logs
-    	read -p "Enter the log file name (with extension, e.g., system.log): " log_file
-    	view_log "$log_file" | sed -E 's/(ERROR|FATAL|CRITICAL)/\o033[31m\1\o033[0m/g' | sed -E 's/\bWARNING\b/\o033[33m&\o033[0m/g' | sed -E 's/INFO/\o033[32m&\o033[0m/g' | sed -E 's/DEBUG/\o033[36m&\o033[0m/g'
+        show_logs
+        read -p "Enter the log file name (with extension, e.g., system.log): " log_file
+        view_log "$log_file" | format_log_output
     elif [ "$option" == "3" ]; then
         search_errors
     elif [ "$option" == "4" ]; then
-    	echo -e "\n\033[96mChoose a log file to tail:\033[0m"
-    	show_logs
-    	read -p "Enter the log file name (with extension, e.g., system.log): " log_file
-	echo -e "\033[96mPress [Ctrl+C] to stop tailing logs\033[0m"
-    	docker exec -it "$CONTAINER_NAME" tail -f "$LOGS_PATH/$log_file" | while IFS= read -r line; do
-        echo "$line" | sed -E 's/(ERROR|FATAL|CRITICAL)/\o033[31m\1\o033[0m/g' | sed -E 's/\bWARNING\b/\o033[33m&\o033[0m/g' | sed -E 's/INFO/\o033[32m&\o033[0m/g' | sed -E 's/DEBUG/\o033[36m&\o033[0m/g' | tee /dev/tty
-    done
-    	echo -e "\033[96mPress [Enter] to return to the menu\033[0m"
-    	read -r -n 1 -s discard
-    	docker exec -it "$CONTAINER_NAME" pkill -f "tail -f $LOGS_PATH/$log_file"
+        echo -e "\n\033[96mChoose an option:\033[0m"
+        echo -e "\033[96m1.\033[0m View all logs in real-time"
+        echo -e "\033[96m2.\033[0m View only error logs in real-time"
 
+        read -p "Enter the option number (1 or 2): " tail_option
+
+        echo -e "\n\033[96mChoose a log file to tail:\033[0m"
+        show_logs
+        read -p "Enter the log file name (with extension, e.g., system.log): " log_file
+
+        echo -e "\033[96mPress [Ctrl+C] to stop tailing logs\033[0m"
+
+        if [ "$tail_option" == "1" ]; then
+            tail_all_logs "$log_file"
+        elif [ "$tail_option" == "2" ]; then
+            tail_error_logs "$log_file"
+        else
+            echo -e "\n\033[91mInvalid choice.\033[0m"
+        fi
+
+        echo -e "\033[96mPress [Enter] to return to the menu\033[0m"
+        read -r -n 1 -s discard
+        docker exec -it "$CONTAINER_NAME" pkill -f "tail -f $LOGS_PATH/$log_file"
     else
         echo -e "\n\033[91mInvalid choice.\033[0m"
         break
