another batch

diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -9,7 +9,7 @@ BASE_URL=${1:-magento2.test}
 bin/stop
 
 docker-compose -f docker-compose.yml up -d
-[ $? != 0 ] && echo "Failed to start Docker services" && exit
+[ "$?" != 0 ] && echo "Failed to start Docker services" && exit
 sleep 5 #Ensure containers are started...
 
 echo "Copying all files from host to container..."
@@ -28,14 +28,14 @@ if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
     echo
     echo
     echo "    Authentication required (repo.magento.com, public_key and private_key):"
-    read -p "        Username: " PUBLIC_KEY
-    read -p "        Password: " PRIVATE_KEY
+    read -r -p "        Username: " PUBLIC_KEY
+    read -r -p "        Password: " PRIVATE_KEY
     echo
     if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ] && hash composer 2>/dev/null; then
-        read -p "    Add authentication information to host composer config? y/n: " ADD_AUTH
+        read -r -p "    Add authentication information to host composer config? y/n: " ADD_AUTH
         echo
         if [[ $ADD_AUTH =~ ^[Yy]$ ]]; then
-            composer global config http-basic.repo.magento.com $PUBLIC_KEY $PRIVATE_KEY
+            composer global config http-basic.repo.magento.com "$PUBLIC_KEY" "$PRIVATE_KEY"
         fi
         ADD_AUTH=''
     fi
@@ -43,7 +43,7 @@ if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
 fi
 
 if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ]; then
-    bin/clinotty composer config http-basic.repo.magento.com $PUBLIC_KEY $PRIVATE_KEY
+    bin/clinotty composer config http-basic.repo.magento.com "$PUBLIC_KEY" "$PRIVATE_KEY"
     PUBLIC_KEY=''
     PRIVATE_KEY=''
 fi
@@ -53,11 +53,11 @@ bin/clinotty composer global require hirak/prestissimo
 bin/clinotty composer update
 
 bin/clinotty bin/magento setup:install \
-  --db-host=$MYSQL_HOST \
-  --db-name=$MYSQL_DATABASE \
-  --db-user=$MYSQL_USER \
-  --db-password=$MYSQL_PASSWORD \
-  --base-url=https://$BASE_URL/ \
+  --db-host="$MYSQL_HOST" \
+  --db-name="$MYSQL_DATABASE" \
+  --db-user="$MYSQL_USER" \
+  --db-password="$MYSQL_PASSWORD" \
+  --base-url=https://"$BASE_URL"/ \
   --admin-firstname=John \
   --admin-lastname=Smith \
   --admin-email=john.smith@gmail.com \
@@ -103,7 +103,7 @@ bin/copyfromcontainer app
 bin/copyfromcontainer vendor
 
 echo "Generating SSL certificate..."
-bin/setup-ssl $BASE_URL
+bin/setup-ssl "$BASE_URL"
 
 echo "Docker development environment setup complete."
 echo "You may now access your Magento instance at https://${BASE_URL}/"
