healthcheck rabbitmq with curl

diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -31,12 +31,12 @@ bin/clinotty timeout $ES_HEALTHCHECK_TIMEOUT bash -c "
 
 echo ""
 echo "Waiting for connection to RabbitMQ..."
-rabbitmqi=10
-until [ $rabbitmqi -le 0 ]; do
-    printf '.'
-    (( rabbitmqi-- ))
-    sleep 2
-done
+bin/clinotty timeout $RABBITMQ_HEALTHCHECK_TIMEOUT bash -c "
+    until curl --silent --output /dev/null http://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$RABBITMQ_HOST:$RABBITMQ_MANAGEMENT_PORT/api/aliveness-test/%2F; do
+        printf '.'
+        sleep 2
+    done"
+[ $? != 0 ] && echo "Failed to connect to RabbitMQ" && exit
 
 bin/clinotty bin/magento setup:install \
   --db-host="$MYSQL_HOST" \
