Improve bin/start and remove backslashes

diff --git a/compose/bin/start b/compose/bin/start
--- a/compose/bin/start
+++ b/compose/bin/start
@@ -1,4 +1,35 @@
 #!/bin/bash
+
+function scanPorts {
+  # Includes ports of Nginx, Mysql, ElasticSearch, Redis, and Rabbitmq
+  local ports="80 443 3306 5672 9200 9300 15672"
+  local mode=$1 # before, after
+  local isValid=true
+
+  for port in $ports; do
+    if [ $mode = "before" ]; then
+      curl --silent --output /dev/null 127.0.0.1:$port
+      if [ $? = 0 ]; then
+        echo "Port [$port] is already allocated"
+        isValid=false
+      fi
+    else # after
+      curl --silent --output /dev/null 127.0.0.1:$port
+      if [ $? != 0 ]; then
+        isValid=false
+      fi
+    fi
+  done
+
+  [ $isValid = true ] && return 0 || return 1
+}
+
+# 1. Scan available ports if docker containers are not running
+docker-compose exec app id >/dev/null 2>&1 || scanPorts "before"
+[ $? != 0 ] && echo "Failed to start docker because some ports are already allocated" && exit 1
+
+# 2. Scan volumn files
+# Check if volume files exist to avoid creating an empty folder
 function parseYaml {
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|,$s\]$s\$|]|" \
@@ -26,21 +57,36 @@ function parseYaml {
   }'
 }
 
-# Check if volume files exist to avoid creating an empty folder
-VOLUME_LIST=`parseYaml docker-compose.dev.yml services_app_volumes`
-IGNORE_LIST="./src/app/code ./src/m2-hotfixes ./src/patches ./src/var/log ./src/var/report ./src"
-IS_VALID=true
-# Loop through all files missing from the docker-compose.dev.yml file
-for file in $VOLUME_LIST; do
-  if [ ! -e $file ] && [[ ! " $IGNORE_LIST " =~ " $file " ]]; then
-    echo "$file: No such file or directory"
-    IS_VALID=false
-  fi
-done
-# Wait to exit until all missing files have been outputted to the user
-[ $IS_VALID = false ] && echo "Failed to start docker for missing volume files" && exit
+function scanVolumeFiles {
+  local volume_list=$1
+  local ignore_list="./src/app/code ./src/m2-hotfixes ./src/patches ./src/var/log ./src/var/report ./src"
+  local isValid=true
 
-docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-orphans "$@"
+  for file in $volume_list; do
+    if [ ! -e $file ] && [[ ! " $ignore_list " =~ " $file " ]]; then
+      echo "$file: No such file or directory"
+      isValid=false
+    fi
+  done
+
+  [ $isValid = true ] && return 0 || return 1
+}
+
+if [ "$1" != "--no-dev" ]; then
+  VOLUME_LIST=$(parseYaml docker-compose.dev.yml services_app_volumes)
+  # Loop through all files missing from the docker-compose.dev.yml file
+  scanVolumeFiles "$VOLUME_LIST"
+  # Wait to exit until all missing files have been outputted to the user
+  [ $? = false ] && echo "Failed to start docker for missing volume files" && exit 1
+fi
+
+# 3. Start all docker container
+if [ "$1" == "--no-dev" ]; then
+  docker-compose -f docker-compose.yml up -d --remove-orphans
+else
+  docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-orphans "$@"
+fi
+[ $? != 0 ] && exit 1
 
 ## Blackfire support
 # ------------------
@@ -48,3 +94,31 @@ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-or
 #bin/root blackfire-agent --register --server-id={YOUR_SERVER_ID} --server-token={YOUR_SERVER_TOKEN}
 ## Then uncomment the below line (and leave uncommented) to start the agent automatically with bin/start:
 #bin/root /etc/init.d/blackfire-agent start
+
+echo "Waiting for all services of containers to be ready..."
+
+# 4. Scan allocated ports, retry 20 times
+count=0
+until [ "$count" -ge 20 ]
+do
+  sleep 1
+  printf "."
+  scanPorts "after" && break
+  count=$((count+1))
+done
+
+# 5. Check service health, retry 20 times
+count=0
+until [ "$count" -ge 20 ]
+do
+  sleep 1
+  printf "."
+  bin/clinotty curl --silent --output /dev/null http://elasticsearch:9200/_cat/health?h=st \
+    && curl --silent --output /dev/null  http://guest:guest@localhost:15672/api/overview \
+    && bin/redis redis-cli ping > /dev/null \
+    && bin/mysql -e "show databases;" >/dev/null \
+    && break
+  count=$((count+1))
+done
+
+echo && echo "All services of containers are started"
