Fix "The current directory is not empty" message appearing on new install (#1140)
Co-authored-by: Michael Lehmkuhl <michael@electricpulp.com>
Co-authored-by: Jenyamba <is3kv3@ukr.net>
Co-authored-by: Tu Van <vandinhtuit@gmail.com>
Co-authored-by: Cid Lopes <alannettto@gmail.com>

diff --git a/lib/onelinesetup b/lib/onelinesetup
--- a/lib/onelinesetup
+++ b/lib/onelinesetup
@@ -5,6 +5,11 @@ DOMAIN=${1:-magento.test}
 VERSION=${2:-2.4.7}
 EDITION=${3:-community}
 
+if [ -d "./bin" ]; then
+  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
+  exit 1
+fi
+
 curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
 
 # &&'s are used below otherwise onelinesetup script fails/errors after bin/download
